version: '3'
services:
    wordpress:
        container_name: wp
        image: wordpress
        volumes:
            -  ./wp_data:/var/www/html
        ports:
            - '80:80'
        environment:
          - WORDPRESS_DB_HOST=mysql
          - WORDPRESS_DB_USER=user
          - WORDPRESS_DB_PASSWORD=password
          - WORDPRESS_DB_NAME=wp 
    mysql:
        container_name: mysql
        image: yobasystems/alpine-mariadb
        volumes:
            - ./bd_data:/var/lib/mysql'
        environment:
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_DATABASE=wp
          - MYSQL_USER=user
          - MYSQL_PASSWORD=password
        expose:
          - "3306"
 

    phpmyadmin:
        container_name: pma
        image: mt08/rpi-phpmyadmin    
        depends_on:      
          - mysql
        ports:      
          - "8080:80"        
        environment:
          - PMA_ROOT_USER=root
          - PMA_USER=user
          - PMA_ARBITARY=1
          - PMA_HOST=mysql
          - PMA_PASSWORD=password    

volumes:
    bd_data: 
    wp_data: 